name: Build (macOS)

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: 'macos-11'
          xcode: '11.7'
        - os: 'macos-11'
          xcode: '12.4'
        - os: 'macos-11'
          xcode: '12.5.1'
        - os: 'macos-11'
          xcode: '13.0'
        - os: 'macos-11'
          xcode: '13.1'
        - os: 'macos-11'
          xcode: '13.2.1'
        - os: 'macos-12'
          xcode: '13.1'
        - os: 'macos-12'
          xcode: '13.2.1'
        - os: 'macos-12'
          xcode: '13.3.1'
        - os: 'macos-12'
          xcode: '13.4'
        - os: 'macos-12'
          xcode: '13.4.1'
        - os: 'macos-12'
          xcode: '14.0'
        - os: 'macos-12'
          xcode: '14.0.1'
        - os: 'macos-12'
          xcode: '14.1'
      fail-fast: false
    
    name: Build (${{ matrix.os }}, Xcode ${{ matrix.xcode }})
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies (macOS)
      run: brew install cairo
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}
    - name: Build
      run: swift build
