name: Build (macOS)

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: 'macos-13'
          xcode: '14.3.1'
      fail-fast: false
    
    name: Build (${{ matrix.os }}, Xcode ${{ matrix.xcode }})
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies (macOS)
      run: brew install cairo
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}
    - name: Build
      run: swift build
