name: Build (Linux)

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-20.04']
        swift: ['5.7', '5.8']
    
    name: Build (${{ matrix.os }}, Swift ${{ matrix.swift }})
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}
    - name: Install system dependencies (Linux)
      run: sudo apt-get update && sudo apt-get install -y libcairo2-dev
    - name: Build
      run: swift build
