name: Build (macOS)

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: ['macos-12']
        xcode: ['13.1', '13.2.1', '13.3.1', '13.4', '13.4.1', '14.0', '14.0.1', '14.1']
      fail-fast: false
    
    name: Build (${{ matrix.os }}, Xcode ${{ matrix.xcode }})
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies (macOS)
      run: brew install cairo
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}
    - name: Build
      run: swift build
